services:

  redis:
    image: redis:7-alpine
    container_name: auromind_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: pgvector/pgvector:pg16
    container_name: auromind_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arunjack007@
      POSTGRES_DB: auromindai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auromindai"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auromind_backend
    env_file:
       - ./backend/.env
    restart: unless-stopped
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --timeout-keep-alive 75"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auromind_celery_worker
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=4 --max-tasks-per-child=100
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auromind_celery_beat
    env_file:
      - ./backend/.env
    restart: unless-stopped
    command: celery -A app.core.celery_app beat --loglevel=info
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auromind_frontend
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: