"""add_agent_lock_and_message_execution

Revision ID: 0a74c81e2e23
Revises: 6d43e6d216a5
Create Date: 2026-06-23 05:32:57.144288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a74c81e2e23'
down_revision: Union[str, Sequence[str], None] = '6d43e6d216a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_executions_conversation_id'), 'message_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_executions_message_id'), 'message_executions', ['message_id'], unique=True)
    op.add_column('conversations', sa.Column('active_agent', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('agent_locked', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('active_workflow_id', sa.UUID(), nullable=True))
    # Safe drops using connection and inspection to prevent transaction aborts
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # 1. Drop index 'ix_wcc_rate_cards_effective_range' if exists
    has_idx1 = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'ix_wcc_rate_cards_effective_range'")).first()
    if has_idx1:
        op.drop_index('ix_wcc_rate_cards_effective_range', table_name='wcc_rate_cards')
        
    # 2. Drop columns from 'wcc_rate_cards' if they exist
    rate_card_cols = [c['name'] for c in inspector.get_columns('wcc_rate_cards')]
    for col in ['meta_cost', 'effective_to', 'customer_price']:
        if col in rate_card_cols:
            op.drop_column('wcc_rate_cards', col)
            
    # 3. Drop index 'ix_wcc_transactions_category' if exists
    has_idx2 = conn.execute(sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'ix_wcc_transactions_category'")).first()
    if has_idx2:
        op.drop_index('ix_wcc_transactions_category', table_name='wcc_transactions')
        
    # 4. Drop columns from 'wcc_transactions' if they exist
    tx_cols = [c['name'] for c in inspector.get_columns('wcc_transactions')]
    for col in ['customer_price_applied', 'meta_cost_applied', 'pricing_version']:
        if col in tx_cols:
            op.drop_column('wcc_transactions', col)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wcc_transactions', sa.Column('pricing_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('wcc_transactions', sa.Column('meta_cost_applied', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.add_column('wcc_transactions', sa.Column('customer_price_applied', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_wcc_transactions_category'), 'wcc_transactions', ['category'], unique=False)
    op.add_column('wcc_rate_cards', sa.Column('customer_price', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.add_column('wcc_rate_cards', sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('wcc_rate_cards', sa.Column('meta_cost', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_wcc_rate_cards_effective_range'), 'wcc_rate_cards', ['category', 'region', 'is_active', 'effective_from', 'effective_to'], unique=False)
    op.drop_column('conversations', 'active_workflow_id')
    op.drop_column('conversations', 'agent_locked')
    op.drop_column('conversations', 'active_agent')
    op.drop_index(op.f('ix_message_executions_message_id'), table_name='message_executions')
    op.drop_index(op.f('ix_message_executions_conversation_id'), table_name='message_executions')
    op.drop_table('message_executions')
    # ### end Alembic commands ###
