"""add_agent_lock_and_message_execution

Revision ID: 0a74c81e2e23
Revises: 6d43e6d216a5
Create Date: 2026-06-23 05:32:57.144288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a74c81e2e23'
down_revision: Union[str, Sequence[str], None] = '6d43e6d216a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_executions_conversation_id'), 'message_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_executions_message_id'), 'message_executions', ['message_id'], unique=True)
    op.add_column('conversations', sa.Column('active_agent', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('agent_locked', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('active_workflow_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_wcc_rate_cards_effective_range'), table_name='wcc_rate_cards')
    op.drop_column('wcc_rate_cards', 'meta_cost')
    op.drop_column('wcc_rate_cards', 'effective_to')
    op.drop_column('wcc_rate_cards', 'customer_price')
    op.drop_index(op.f('ix_wcc_transactions_category'), table_name='wcc_transactions')
    op.drop_column('wcc_transactions', 'customer_price_applied')
    op.drop_column('wcc_transactions', 'meta_cost_applied')
    op.drop_column('wcc_transactions', 'pricing_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wcc_transactions', sa.Column('pricing_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('wcc_transactions', sa.Column('meta_cost_applied', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.add_column('wcc_transactions', sa.Column('customer_price_applied', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_wcc_transactions_category'), 'wcc_transactions', ['category'], unique=False)
    op.add_column('wcc_rate_cards', sa.Column('customer_price', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.add_column('wcc_rate_cards', sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('wcc_rate_cards', sa.Column('meta_cost', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_wcc_rate_cards_effective_range'), 'wcc_rate_cards', ['category', 'region', 'is_active', 'effective_from', 'effective_to'], unique=False)
    op.drop_column('conversations', 'active_workflow_id')
    op.drop_column('conversations', 'agent_locked')
    op.drop_column('conversations', 'active_agent')
    op.drop_index(op.f('ix_message_executions_message_id'), table_name='message_executions')
    op.drop_index(op.f('ix_message_executions_conversation_id'), table_name='message_executions')
    op.drop_table('message_executions')
    # ### end Alembic commands ###
