"""add is_favorite to leads

Revision ID: 0f149dffe0f3
Revises: 9f4f9420d3d1
Create Date: 2026-05-30 12:22:00.788306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f149dffe0f3'
down_revision: Union[str, Sequence[str], None] = '9f4f9420d3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'is_favorite')
    # ### end Alembic commands ###
