"""add_wcc_indexes

Revision ID: 18046b90ce50
Revises: 7527fcdb71dd
Create Date: 2026-06-18 09:50:30.803699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18046b90ce50'
down_revision: Union[str, Sequence[str], None] = '7527fcdb71dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wcc_rate_cards_lookup', 'wcc_rate_cards', ['category', 'region', 'is_active'], unique=False)
    op.create_index('ix_wcc_transactions_meta_session', 'wcc_transactions', ['meta_session_id'], unique=False)
    op.create_index('ix_wcc_transactions_workspace_created', 'wcc_transactions', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wcc_transactions_workspace_created', table_name='wcc_transactions')
    op.drop_index('ix_wcc_transactions_meta_session', table_name='wcc_transactions')
    op.drop_index('ix_wcc_rate_cards_lookup', table_name='wcc_rate_cards')
    # ### end Alembic commands ###
