"""add two factor columns

Revision ID: 18068968afb9
Revises: b457c7d1b080
Create Date: 2026-07-06 12:01:52.160457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18068968afb9'
down_revision: Union[str, Sequence[str], None] = 'b457c7d1b080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('feature_key', sa.String(length=100), nullable=True))
    op.add_column('model_configs', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column(
    'model_configs',
    sa.Column(
        'fallback_enabled',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)
    op.add_column('model_configs', sa.Column('fallback_provider', sa.String(length=50), nullable=True))
    op.add_column('model_configs', sa.Column('fallback_model', sa.String(length=200), nullable=True))
    op.drop_index('ix_model_configs_name', table_name='model_configs')
    op.create_index(op.f('ix_model_configs_name'), 'model_configs', ['name'], unique=False)
    op.create_index(op.f('ix_model_configs_experience_level'), 'model_configs', ['experience_level'], unique=False)
    op.create_index(op.f('ix_model_configs_feature_key'), 'model_configs', ['feature_key'], unique=False)
    op.create_unique_constraint('uq_model_configs_feature_experience', 'model_configs', ['feature_key', 'experience_level'])
    op.add_column(
    "plan_entitlements",
    sa.Column(
        "flow",
        sa.Integer(),
        nullable=False,
        server_default="0"
    )
)

    op.alter_column(
        "plan_entitlements",
        "flow",
        server_default=None
    )
    op.add_column('token_ledger', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('token_ledger', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('token_ledger', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('token_ledger', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('token_ledger', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('token_ledger', sa.Column('request_id', sa.String(length=255), nullable=True))
    op.add_column('token_ledger', sa.Column('execution_id', sa.String(length=255), nullable=True))
    op.add_column('token_ledger', sa.Column('feature_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_token_ledger_execution_id'), 'token_ledger', ['execution_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_feature_key'), 'token_ledger', ['feature_key'], unique=False)
    op.add_column('wcc_rate_cards', sa.Column('meta_cost', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('wcc_rate_cards', sa.Column('customer_price', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('wcc_rate_cards', sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('wcc_rate_cards', 'rate_per_message',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    op.create_index('ix_wcc_rate_cards_effective_range', 'wcc_rate_cards', ['category', 'region', 'is_active', 'effective_from', 'effective_to'], unique=False)
    op.add_column('wcc_transactions', sa.Column('meta_cost_applied', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('wcc_transactions', sa.Column('customer_price_applied', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('wcc_transactions', sa.Column('pricing_version', sa.Integer(), nullable=False))
    op.create_index('ix_wcc_transactions_category', 'wcc_transactions', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wcc_transactions_category', table_name='wcc_transactions')
    op.drop_column('wcc_transactions', 'pricing_version')
    op.drop_column('wcc_transactions', 'customer_price_applied')
    op.drop_column('wcc_transactions', 'meta_cost_applied')
    op.drop_index('ix_wcc_rate_cards_effective_range', table_name='wcc_rate_cards')
    op.alter_column('wcc_rate_cards', 'rate_per_message',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.drop_column('wcc_rate_cards', 'effective_to')
    op.drop_column('wcc_rate_cards', 'customer_price')
    op.drop_column('wcc_rate_cards', 'meta_cost')
    op.drop_index(op.f('ix_token_ledger_feature_key'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_execution_id'), table_name='token_ledger')
    op.drop_column('token_ledger', 'feature_key')
    op.drop_column('token_ledger', 'execution_id')
    op.drop_column('token_ledger', 'request_id')
    op.drop_column('token_ledger', 'total_tokens')
    op.drop_column('token_ledger', 'completion_tokens')
    op.drop_column('token_ledger', 'prompt_tokens')
    op.drop_column('token_ledger', 'model')
    op.drop_column('token_ledger', 'provider')
    op.drop_column('plan_entitlements', 'flow')
    op.drop_constraint('uq_model_configs_feature_experience', 'model_configs', type_='unique')
    op.drop_index(op.f('ix_model_configs_feature_key'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_experience_level'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_name'), table_name='model_configs')
    op.create_index('ix_model_configs_name', 'model_configs', ['name'], unique=True)
    op.drop_column('model_configs', 'fallback_model')
    op.drop_column('model_configs', 'fallback_provider')
    op.drop_column('model_configs', 'fallback_enabled')
    op.drop_column('model_configs', 'experience_level')
    op.drop_column('model_configs', 'feature_key')
    # ### end Alembic commands ###
