"""add archived fields

Revision ID: 33c359e5cf2d
Revises: b5b7d55a8b10
Create Date: 2026-05-27 05:42:55.855325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33c359e5cf2d'
down_revision: Union[str, Sequence[str], None] = 'b5b7d55a8b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('archive_location', sa.String(), nullable=True))

    op.add_column('workspace_ai_configs', sa.Column('last_agent', sa.String(length=50), nullable=True))
    op.add_column('workspace_ai_configs', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_ai_configs', 'custom_fields')
    op.drop_column('workspace_ai_configs', 'last_agent')
    op.drop_column('leads', 'archive_location')
    op.drop_column('leads', 'archived_at')
    # ### end Alembic commands ###
