"""Add new CRM elements to Lead module

Revision ID: 39ced29854e5
Revises: 87ecf7cc6c83
Create Date: 2026-05-20 17:05:21.246151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ced29854e5'
down_revision: Union[str, Sequence[str], None] = '87ecf7cc6c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ADD COLUMN TEMPORARILY NULLABLE
    op.add_column(
        'outbound_messages',
        sa.Column(
            'message_type',
            sa.String(length=50),
            nullable=True,
            server_default='automation'
        )
    )

    # UPDATE EXISTING ROWS
    op.execute("""
        UPDATE outbound_messages
        SET message_type = 'automation'
        WHERE message_type IS NULL
    """)

    # MAKE COLUMN NOT NULL
    op.alter_column(
        'outbound_messages',
        'message_type',
        nullable=False
    )

    # CREATE INDEX
    op.create_index(
        op.f('ix_outbound_messages_message_type'),
        'outbound_messages',
        ['message_type'],
        unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_messages_message_type'), table_name='outbound_messages')
    op.drop_column('outbound_messages', 'message_type')
    # ### end Alembic commands ###
