"""add lead scoring redesign

Revision ID: 4850d34b7159
Revises: d3b841a129f1
Create Date: 2026-05-22 12:57:21.308794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4850d34b7159'
down_revision: Union[str, Sequence[str], None] = 'd3b841a129f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # lead_score_history
    op.add_column(
        'lead_score_history',
        sa.Column(
            'behavioral_score_delta',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'lead_score_history',
        sa.Column(
            'intent_score_delta',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'lead_score_history',
        sa.Column(
            'event_type',
            sa.String(length=100),
            nullable=False,
            server_default='system'
        )
    )

    # leads table
    op.add_column(
        'leads',
        sa.Column(
            'behavioral_score',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'leads',
        sa.Column(
            'semantic_intent_score',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'leads',
        sa.Column(
            'lead_tier',
            sa.String(length=50),
            nullable=False,
            server_default='cold'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'lead_tier')
    op.drop_column('leads', 'semantic_intent_score')
    op.drop_column('leads', 'behavioral_score')
    op.drop_column('lead_score_history', 'event_type')
    op.drop_column('lead_score_history', 'intent_score_delta')
    op.drop_column('lead_score_history', 'behavioral_score_delta')
    # ### end Alembic commands ###
