"""replace contact with phone

Revision ID: 55f90eddbc3c
Revises: e80f04b3d2e1
Create Date: 2026-05-21 11:45:28.233604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55f90eddbc3c'
down_revision: Union[str, Sequence[str], None] = 'e80f04b3d2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_conversation_id'), 'lead_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_lead_events_created_at'), 'lead_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_events_event_type'), 'lead_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_events_workspace_id'), 'lead_events', ['workspace_id'], unique=False)
    op.create_table('lead_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('score_before', sa.Integer(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_score_history_created_at'), 'lead_score_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_score_history_lead_id'), 'lead_score_history', ['lead_id'], unique=False)
    op.create_table('template_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_type', sa.String(length=50), nullable=True),
    sa.Column('score_impact', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_logs_lead_id'), 'template_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_template_logs_template_id'), 'template_logs', ['template_id'], unique=False)
    op.drop_table('rag_feedback_legacy_archive')
    op.drop_table('learning_data_legacy_archive')
    op.drop_table('leads_legacy_archive')
    op.drop_table('followups_chat_legacy_archive')
    op.drop_table('conversation_states_legacy_archive')
    op.drop_table('support_tickets_legacy_archive')
    op.drop_table('followups_legacy_archive')
    op.drop_table('sales_pipeline_legacy_archive')
    op.drop_table('human_escalations_legacy_archive')
    op.drop_constraint(op.f('conversation_states_user_id_fkey'), 'conversation_states', type_='foreignkey')
    op.drop_column('conversation_states', 'user_id')
    op.alter_column('conversations', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'human_escalations', 'users', ['user_id'], ['id'])
    op.alter_column('impersonation_sessions', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('leads', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('current_node', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('total_nodes', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('leads', sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('leads', sa.Column('budget_raw', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('template_attempts', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leads_last_activity_at'), 'leads', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.drop_constraint(op.f('leads_user_id_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('leads', 'user_id')
    op.drop_column('leads', 'intent_signals')
    op.drop_column('leads', 'intent_bonus')
    op.drop_column('leads', 'contact')
    op.create_index(op.f('ix_mcp_rules_workspace_id'), 'mcp_rules', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('sales_pipeline_user_id_fkey'), 'sales_pipeline', type_='foreignkey')
    op.drop_column('sales_pipeline', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_pipeline', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('sales_pipeline_user_id_fkey'), 'sales_pipeline', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_mcp_rules_workspace_id'), table_name='mcp_rules')
    op.add_column('leads', sa.Column('contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('intent_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('intent_signals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_user_id_fkey'), 'leads', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_last_activity_at'), table_name='leads')
    op.drop_column('leads', 'assigned_to')
    op.drop_column('leads', 'last_activity_at')
    op.drop_column('leads', 'template_attempts')
    op.drop_column('leads', 'budget_raw')
    op.drop_column('leads', 'budget_max')
    op.drop_column('leads', 'budget_min')
    op.drop_column('leads', 'score')
    op.drop_column('leads', 'total_nodes')
    op.drop_column('leads', 'current_node')
    op.drop_column('leads', 'status')
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'phone')
    op.alter_column('impersonation_sessions', 'session_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'human_escalations', type_='foreignkey')
    op.alter_column('conversations', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('conversation_states', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('conversation_states_user_id_fkey'), 'conversation_states', 'users', ['user_id'], ['id'])
    op.create_table('human_escalations_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('sales_pipeline_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('interest_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('objections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('followups_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followup_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mcp_decision', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mcp_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('support_tickets_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('issue_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('conversation_states_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('current_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_intent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_agent', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('followup_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('repeat_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_message_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('followups_chat_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('followup_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_followup_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('leads_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('requirement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timeline', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('qualification', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('learning_data_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('rag_feedback_legacy_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rewritten_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('selected_tool', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_template_logs_template_id'), table_name='template_logs')
    op.drop_index(op.f('ix_template_logs_lead_id'), table_name='template_logs')
    op.drop_table('template_logs')
    op.drop_index(op.f('ix_lead_score_history_lead_id'), table_name='lead_score_history')
    op.drop_index(op.f('ix_lead_score_history_created_at'), table_name='lead_score_history')
    op.drop_table('lead_score_history')
    op.drop_index(op.f('ix_lead_events_workspace_id'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_event_type'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_created_at'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_conversation_id'), table_name='lead_events')
    op.drop_table('lead_events')
    # ### end Alembic commands ###
