"""fix external_id

Revision ID: 5d94b98b2d59
Revises: 161d0c55891a
Create Date: 2026-04-15 16:32:41.103154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d94b98b2d59'
down_revision: Union[str, Sequence[str], None] = '161d0c55891a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automation_flows_name', table_name='automation_flows')
    op.drop_index('ix_automation_flows_workspace_id', table_name='automation_flows')
    op.drop_table('automation_flows')
    op.drop_index('ix_calendar_events_google_event_id', table_name='calendar_events')
    op.drop_index('ix_calendar_events_workspace_id', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_table('rag_feedback')
    op.drop_table('learning_data')
    op.drop_index('ix_email_reply_logs_message_id', table_name='email_reply_logs')
    op.drop_index('ix_email_reply_logs_thread_id', table_name='email_reply_logs')
    op.drop_index('ix_email_reply_logs_workspace_id', table_name='email_reply_logs')
    op.drop_table('email_reply_logs')
    op.drop_index('ix_integrations_workspace_id', table_name='integrations')
    op.drop_table('integrations')
    op.alter_column('messages', 'external_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.alter_column('messages', 'external_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('connected_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connected_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='integrations_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='integrations_pkey')
    )
    op.create_index('ix_integrations_workspace_id', 'integrations', ['workspace_id'], unique=False)
    op.create_table('email_reply_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reply_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='email_reply_logs_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_reply_logs_pkey')
    )
    op.create_index('ix_email_reply_logs_workspace_id', 'email_reply_logs', ['workspace_id'], unique=False)
    op.create_index('ix_email_reply_logs_thread_id', 'email_reply_logs', ['thread_id'], unique=False)
    op.create_index('ix_email_reply_logs_message_id', 'email_reply_logs', ['message_id'], unique=False)
    op.create_table('learning_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='learning_data_pkey')
    )
    op.create_table('rag_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rewritten_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('selected_tool', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rag_feedback_pkey')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('google_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='calendar_events_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='calendar_events_pkey')
    )
    op.create_index('ix_calendar_events_workspace_id', 'calendar_events', ['workspace_id'], unique=False)
    op.create_index('ix_calendar_events_google_event_id', 'calendar_events', ['google_event_id'], unique=False)
    op.create_table('automation_flows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('edges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='automation_flows_pkey')
    )
    op.create_index('ix_automation_flows_workspace_id', 'automation_flows', ['workspace_id'], unique=False)
    op.create_index('ix_automation_flows_name', 'automation_flows', ['name'], unique=False)
    # ### end Alembic commands ###
