"""restore intent scoring fields

Revision ID: 642213736b03
Revises: 55f90eddbc3c
Create Date: 2026-05-21 12:03:57.668194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642213736b03'
down_revision: Union[str, Sequence[str], None] = '55f90eddbc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('intent_bonus', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('intent_signals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'intent_signals')
    op.drop_column('leads', 'intent_bonus')
    # ### end Alembic commands ###
