"""add user_id to leads

Revision ID: 6b8c6b2bcba9
Revises: 14f2041764be
Create Date: 2026-05-26 07:38:44.783901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8c6b2bcba9'
down_revision: Union[str, Sequence[str], None] = '14f2041764be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_ai_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('lead_fields', sa.JSON(), nullable=True),
    sa.Column('rag_enabled', sa.Boolean(), nullable=True),
    sa.Column('calendar_enabled', sa.Boolean(), nullable=True),
    sa.Column('payment_enabled', sa.Boolean(), nullable=True),
    sa.Column('support_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.add_column('human_escalations', sa.Column('assigned_to', sa.UUID(), nullable=True))
    op.add_column('human_escalations', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('human_escalations', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('human_escalations', sa.Column('resolution_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('custom_fields', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('lead_score', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('demo_requested', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('meeting_link', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('payment_link', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('last_agent', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'])
    op.add_column('sales_pipeline', sa.Column('deal_value', sa.Float(), nullable=True))
    op.add_column('sales_pipeline', sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_pipeline', sa.Column('payment_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_pipeline', 'payment_completed')
    op.drop_column('sales_pipeline', 'expected_close_date')
    op.drop_column('sales_pipeline', 'deal_value')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'ai_summary')
    op.drop_column('leads', 'last_agent')
    op.drop_column('leads', 'payment_link')
    op.drop_column('leads', 'payment_status')
    op.drop_column('leads', 'meeting_link')
    op.drop_column('leads', 'meeting_date')
    op.drop_column('leads', 'demo_requested')
    op.drop_column('leads', 'lead_score')
    op.drop_column('leads', 'custom_fields')
    op.drop_column('leads', 'user_id')
    op.drop_column('human_escalations', 'resolution_notes')
    op.drop_column('human_escalations', 'resolved_at')
    op.drop_column('human_escalations', 'priority')
    op.drop_column('human_escalations', 'assigned_to')
    op.drop_table('workspace_ai_configs')
    # ### end Alembic commands ###
