"""add wcc wallet tables

Revision ID: 7527fcdb71dd
Revises: 7273795b5903
Create Date: 2026-06-18 09:33:22.184421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7527fcdb71dd'
down_revision: Union[str, Sequence[str], None] = '7273795b5903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wcc_rate_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('rate_per_message', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wcc_recharge_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wcc_recharge_logs_gateway_order_id'), 'wcc_recharge_logs', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_wcc_recharge_logs_gateway_payment_id'), 'wcc_recharge_logs', ['gateway_payment_id'], unique=True)
    op.create_index(op.f('ix_wcc_recharge_logs_workspace_id'), 'wcc_recharge_logs', ['workspace_id'], unique=False)
    op.create_table('wcc_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('meta_session_id', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'meta_session_id', name='uq_wcc_transaction_workspace_session')
    )
    op.create_index(op.f('ix_wcc_transactions_created_at'), 'wcc_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wcc_transactions_workspace_id'), 'wcc_transactions', ['workspace_id'], unique=False)
    op.create_table('wcc_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wcc_wallets_workspace_id'), 'wcc_wallets', ['workspace_id'], unique=True)
    
    # Seed default India (IN) rates idempotently
    op.execute(
        """
        INSERT INTO wcc_rate_cards (id, category, region, rate_per_message, is_active, effective_from, created_at, updated_at)
        VALUES 
          ('a1e2f3b4-5c6d-7e8f-9a0b-1c2d3e4f5a6b', 'marketing', 'IN', 1.09, true, NOW(), NOW(), NOW()),
          ('b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'utility', 'IN', 0.145, true, NOW(), NOW(), NOW()),
          ('c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'authentication', 'IN', 0.145, true, NOW(), NOW(), NOW()),
          ('d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'service', 'IN', 0.00, true, NOW(), NOW(), NOW())
        ON CONFLICT (id) DO NOTHING;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wcc_wallets_workspace_id'), table_name='wcc_wallets')
    op.drop_table('wcc_wallets')
    op.drop_index(op.f('ix_wcc_transactions_workspace_id'), table_name='wcc_transactions')
    op.drop_index(op.f('ix_wcc_transactions_created_at'), table_name='wcc_transactions')
    op.drop_table('wcc_transactions')
    op.drop_index(op.f('ix_wcc_recharge_logs_workspace_id'), table_name='wcc_recharge_logs')
    op.drop_index(op.f('ix_wcc_recharge_logs_gateway_payment_id'), table_name='wcc_recharge_logs')
    op.drop_index(op.f('ix_wcc_recharge_logs_gateway_order_id'), table_name='wcc_recharge_logs')
    op.drop_table('wcc_recharge_logs')
    op.drop_table('wcc_rate_cards')
    # ### end Alembic commands ###
