"""Add new CRM elements to Lead module

Revision ID: 7758fe8aa2cb
Revises: ff1a2b3c4d5e
Create Date: 2026-05-09 17:15:05.289507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7758fe8aa2cb'
down_revision: Union[str, Sequence[str], None] = 'ff1a2b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_events_provider_event_id', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_integrations_workspace_id', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('ix_calendar_events_google_event_id', table_name='calendar_events')
    op.drop_index('ix_calendar_events_workspace_id', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_email_reply_logs_message_id', table_name='email_reply_logs')
    op.drop_index('ix_email_reply_logs_thread_id', table_name='email_reply_logs')
    op.drop_index('ix_email_reply_logs_workspace_id', table_name='email_reply_logs')
    op.drop_table('email_reply_logs')
    op.drop_index('ix_usage_subscription_id', table_name='usage')
    op.drop_index('ix_usage_workspace_id', table_name='usage')
    op.drop_table('usage')
    op.drop_table('templates')
    op.drop_table('payment_settings')
    op.drop_index('ix_automation_flows_name', table_name='automation_flows')
    op.drop_index('ix_automation_flows_workspace_id', table_name='automation_flows')
    op.drop_table('automation_flows')
    op.create_unique_constraint('uq_workspace_phone_channel', 'conversations', ['workspace_id', 'phone', 'channel'])
    op.create_unique_constraint('uq_message_external_id', 'messages', ['external_id'])
    op.create_unique_constraint('uq_workspace_user', 'workspace_members', ['workspace_id', 'user_id'])
    op.alter_column('workspaces', 'provider_customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_workspaces_provider_customer_id'), 'workspaces', ['provider_customer_id'], unique=False)
    op.create_foreign_key(None, 'workspaces', 'users', ['billing_owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_index(op.f('ix_workspaces_provider_customer_id'), table_name='workspaces')
    op.alter_column('workspaces', 'provider_customer_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_workspace_user', 'workspace_members', type_='unique')
    op.drop_constraint('uq_message_external_id', 'messages', type_='unique')
    op.drop_constraint('uq_workspace_phone_channel', 'conversations', type_='unique')
    op.create_table('automation_flows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('edges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='automation_flows_pkey')
    )
    op.create_index('ix_automation_flows_workspace_id', 'automation_flows', ['workspace_id'], unique=False)
    op.create_index('ix_automation_flows_name', 'automation_flows', ['name'], unique=False)
    op.create_table('payment_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('razorpay_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('razorpay_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paypal_client', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('paypal_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_settings_pkey')
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_template_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='templates_pkey')
    )
    op.create_table('usage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('messages_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overage_messages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overage_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('billed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='usage_subscription_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='usage_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usage_pkey'),
    sa.UniqueConstraint('workspace_id', 'subscription_id', 'period_start', name='uq_usage_period', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_usage_workspace_id', 'usage', ['workspace_id'], unique=False)
    op.create_index('ix_usage_subscription_id', 'usage', ['subscription_id'], unique=False)
    op.create_table('email_reply_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reply_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='email_reply_logs_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_reply_logs_pkey')
    )
    op.create_index('ix_email_reply_logs_workspace_id', 'email_reply_logs', ['workspace_id'], unique=False)
    op.create_index('ix_email_reply_logs_thread_id', 'email_reply_logs', ['thread_id'], unique=False)
    op.create_index('ix_email_reply_logs_message_id', 'email_reply_logs', ['message_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('google_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='calendar_events_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='calendar_events_pkey')
    )
    op.create_index('ix_calendar_events_workspace_id', 'calendar_events', ['workspace_id'], unique=False)
    op.create_index('ix_calendar_events_google_event_id', 'calendar_events', ['google_event_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('connected_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connected_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='integrations_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='integrations_pkey')
    )
    op.create_index('ix_integrations_workspace_id', 'integrations', ['workspace_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('provider_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='webhook_events_pkey'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_event_id', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_webhook_events_provider_event_id', 'webhook_events', ['provider_event_id'], unique=False)
    # ### end Alembic commands ###
