"""add_gst_billing_system

Revision ID: 8c3cf45c6c75
Revises: 63db3e63a669
Create Date: 2026-07-30 11:57:51.311267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c3cf45c6c75'
down_revision: Union[str, Sequence[str], None] = '63db3e63a669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sequences',
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.alter_column('chat_messages', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'COMPLETED'::character varying"))
    op.add_column('flow_pack_purchases', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('place_of_supply', sa.String(length=100), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('customer_state', sa.String(length=100), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('customer_country', sa.String(length=100), nullable=True))
    op.add_column('flow_pack_purchases', sa.Column('customer_gstin', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_flow_pack_purchases_status'), table_name='flow_pack_purchases')
    op.add_column('invoices', sa.Column('payment_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('flow_pack_purchase_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('wcc_recharge_log_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('product_type', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('place_of_supply', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('supplier_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('supplier_gstin', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('supplier_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('supplier_state', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('supplier_country', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('customer_gstin', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('customer_address', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('customer_state', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('customer_country', sa.String(length=100), nullable=True))
    op.alter_column('invoices', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_foreign_key(None, 'invoices', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'wcc_recharge_logs', ['wcc_recharge_log_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'flow_pack_purchases', ['flow_pack_purchase_id'], ['id'], ondelete='SET NULL')
    op.add_column('payments', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('payments', sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('payments', sa.Column('place_of_supply', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('customer_state', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('customer_country', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('customer_gstin', sa.String(length=50), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('place_of_supply', sa.String(length=100), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('customer_state', sa.String(length=100), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('customer_country', sa.String(length=100), nullable=True))
    op.add_column('wcc_recharge_logs', sa.Column('customer_gstin', sa.String(length=50), nullable=True))
    op.add_column('workspaces', sa.Column('billing_state', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('billing_country', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('billing_gstin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'billing_gstin')
    op.drop_column('workspaces', 'billing_address')
    op.drop_column('workspaces', 'billing_country')
    op.drop_column('workspaces', 'billing_state')
    op.drop_column('wcc_recharge_logs', 'customer_gstin')
    op.drop_column('wcc_recharge_logs', 'customer_country')
    op.drop_column('wcc_recharge_logs', 'customer_state')
    op.drop_column('wcc_recharge_logs', 'place_of_supply')
    op.drop_column('wcc_recharge_logs', 'total_amount')
    op.drop_column('wcc_recharge_logs', 'taxable_amount')
    op.drop_column('wcc_recharge_logs', 'igst')
    op.drop_column('wcc_recharge_logs', 'sgst')
    op.drop_column('wcc_recharge_logs', 'cgst')
    op.drop_column('wcc_recharge_logs', 'gst_amount')
    op.drop_column('wcc_recharge_logs', 'gst_rate')
    op.drop_column('payments', 'customer_gstin')
    op.drop_column('payments', 'customer_country')
    op.drop_column('payments', 'customer_state')
    op.drop_column('payments', 'place_of_supply')
    op.drop_column('payments', 'total_amount')
    op.drop_column('payments', 'taxable_amount')
    op.drop_column('payments', 'igst')
    op.drop_column('payments', 'sgst')
    op.drop_column('payments', 'cgst')
    op.drop_column('payments', 'gst_amount')
    op.drop_column('payments', 'gst_rate')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('invoices', 'customer_country')
    op.drop_column('invoices', 'customer_state')
    op.drop_column('invoices', 'customer_address')
    op.drop_column('invoices', 'customer_gstin')
    op.drop_column('invoices', 'customer_name')
    op.drop_column('invoices', 'supplier_country')
    op.drop_column('invoices', 'supplier_state')
    op.drop_column('invoices', 'supplier_address')
    op.drop_column('invoices', 'supplier_gstin')
    op.drop_column('invoices', 'supplier_name')
    op.drop_column('invoices', 'place_of_supply')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'taxable_amount')
    op.drop_column('invoices', 'igst')
    op.drop_column('invoices', 'sgst')
    op.drop_column('invoices', 'cgst')
    op.drop_column('invoices', 'gst_amount')
    op.drop_column('invoices', 'gst_rate')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'product_type')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'wcc_recharge_log_id')
    op.drop_column('invoices', 'flow_pack_purchase_id')
    op.drop_column('invoices', 'payment_id')
    op.create_index(op.f('ix_flow_pack_purchases_status'), 'flow_pack_purchases', ['status'], unique=False)
    op.drop_column('flow_pack_purchases', 'customer_gstin')
    op.drop_column('flow_pack_purchases', 'customer_country')
    op.drop_column('flow_pack_purchases', 'customer_state')
    op.drop_column('flow_pack_purchases', 'place_of_supply')
    op.drop_column('flow_pack_purchases', 'total_amount')
    op.drop_column('flow_pack_purchases', 'taxable_amount')
    op.drop_column('flow_pack_purchases', 'igst')
    op.drop_column('flow_pack_purchases', 'sgst')
    op.drop_column('flow_pack_purchases', 'cgst')
    op.drop_column('flow_pack_purchases', 'gst_amount')
    op.drop_column('flow_pack_purchases', 'gst_rate')
    op.drop_column('flow_pack_purchases', 'subtotal')
    op.drop_table('invoice_sequences')
    # ### end Alembic commands ###
