"""upgrade version 2.0

Revision ID: 92b7f7ad67c2
Revises: 633237a43e48
Create Date: 2026-05-27 12:58:58.527146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b7f7ad67c2'
down_revision: Union[str, Sequence[str], None] = '633237a43e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twilio_configs')
    op.drop_table('mcp_rules')
    op.drop_table('workspace_ai_configs')
    op.drop_index('ix_promises_workspace_id', table_name='promises')
    op.drop_table('promises')
    op.drop_table('followups_chat')
    op.drop_index('ix_email_states_workspace_id', table_name='email_states')
    op.drop_table('email_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_email_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='email_states_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_states_pkey')
    )
    op.create_index('ix_email_states_workspace_id', 'email_states', ['workspace_id'], unique=True)
    op.create_table('followups_chat',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('followup_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_followup_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='followups_chat_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='followups_chat_pkey')
    )
    op.create_table('promises',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ai_action_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ai_action_id'], ['ai_actions.id'], name='promises_ai_action_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='promises_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='promises_workspace_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='promises_pkey')
    )
    op.create_index('ix_promises_workspace_id', 'promises', ['workspace_id'], unique=False)
    op.create_table('workspace_ai_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lead_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rag_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('calendar_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('support_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='workspace_ai_configs_pkey'),
    sa.UniqueConstraint('workspace_id', name='workspace_ai_configs_workspace_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('mcp_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mcp_rules_pkey')
    )
    op.create_table('twilio_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='twilio_configs_workspace_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='twilio_configs_pkey'),
    sa.UniqueConstraint('phone_number', name='twilio_configs_phone_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
