"""add flow limit and purchased flow packs

Revision ID: ab9651d8f2a4
Revises: 6d43e6d216a5
Create Date: 2026-06-23 06:57:27.872428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9651d8f2a4'
down_revision: Union[str, Sequence[str], None] = '6d43e6d216a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchased_flow_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('flows', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchased_flow_packs_workspace_id'), 'purchased_flow_packs', ['workspace_id'], unique=False)
    op.add_column('plan_entitlements', sa.Column('flow', sa.Integer(), nullable=True))
    op.execute("UPDATE plan_entitlements SET flow = 5")
    op.alter_column('plan_entitlements', 'flow', nullable=False)
    op.alter_column('wcc_rate_cards', 'rate_per_message',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    op.alter_column('wcc_rate_cards', 'meta_cost',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    op.alter_column('wcc_rate_cards', 'customer_price',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    op.alter_column('wcc_transactions', 'meta_cost_applied',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    op.alter_column('wcc_transactions', 'customer_price_applied',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wcc_transactions', 'customer_price_applied',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.alter_column('wcc_transactions', 'meta_cost_applied',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.alter_column('wcc_rate_cards', 'customer_price',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.alter_column('wcc_rate_cards', 'meta_cost',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.alter_column('wcc_rate_cards', 'rate_per_message',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False)
    op.drop_column('plan_entitlements', 'flow')
    op.drop_index(op.f('ix_purchased_flow_packs_workspace_id'), table_name='purchased_flow_packs')
    op.drop_table('purchased_flow_packs')
    # ### end Alembic commands ###
