"""add human takeover state

Revision ID: b5b7d55a8b10
Revises: 6b8c6b2bcba9
Create Date: 2026-05-26 11:59:34.902469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b7d55a8b10'
down_revision: Union[str, Sequence[str], None] = '6b8c6b2bcba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_states', sa.Column('human_takeover', sa.Boolean(), nullable=True))
    op.add_column('conversation_states', sa.Column('ai_paused_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_states', 'ai_paused_at')
    op.drop_column('conversation_states', 'human_takeover')
    # ### end Alembic commands ###
