"""add learning_data table

Revision ID: bfb5103dad12
Revises: d3e91e9bc870
Create Date: 2026-03-25 17:17:53.613150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfb5103dad12'
down_revision: Union[str, Sequence[str], None] = 'd3e91e9bc870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # Safe drop tables with their indexes
    for idx, table in [
        ('ix_integrations_workspace_id', 'integrations'),
        ('ix_automation_flows_name', 'automation_flows'),
        ('ix_automation_flows_workspace_id', 'automation_flows'),
        ('ix_email_reply_logs_message_id', 'email_reply_logs'),
        ('ix_email_reply_logs_thread_id', 'email_reply_logs'),
        ('ix_email_reply_logs_workspace_id', 'email_reply_logs'),
        ('ix_calendar_events_google_event_id', 'calendar_events'),
        ('ix_calendar_events_workspace_id', 'calendar_events'),
    ]:
        conn.execute(sa.text(f"DROP INDEX IF EXISTS {idx}"))

    for table in ['integrations', 'automation_flows', 'email_reply_logs', 'calendar_events']:
        exists = conn.execute(sa.text(
            f"SELECT 1 FROM information_schema.tables WHERE table_name='{table}'"
        )).fetchone()
        if exists:
            op.drop_table(table)

    # Safe create indexes
    for idx, table, cols in [
        ('ix_conversations_id', 'conversations', ['id']),
        ('ix_conversations_user_id', 'conversations', ['user_id']),
        ('ix_conversations_workspace_id', 'conversations', ['workspace_id']),
    ]:
        exists = conn.execute(sa.text(
            f"SELECT 1 FROM pg_indexes WHERE indexname = '{idx}'"
        )).fetchone()
        if not exists:
            op.create_index(idx, table, cols, unique=False)

    # Safe drop columns
    for table, col in [
        ('conversations', 'title'),
        ('messages', 'created_at'),
        ('messages', 'role'),
    ]:
        exists = conn.execute(sa.text(
            f"SELECT 1 FROM information_schema.columns "
            f"WHERE table_name='{table}' AND column_name='{col}'"
        )).fetchone()
        if exists:
            op.drop_column(table, col)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.add_column('conversations', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('google_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('calendar_events_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_events_pkey'))
    )
    op.create_index(op.f('ix_calendar_events_workspace_id'), 'calendar_events', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_google_event_id'), 'calendar_events', ['google_event_id'], unique=False)
    op.create_table('email_reply_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reply_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('email_reply_logs_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('email_reply_logs_pkey'))
    )
    op.create_index(op.f('ix_email_reply_logs_workspace_id'), 'email_reply_logs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_email_reply_logs_thread_id'), 'email_reply_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_reply_logs_message_id'), 'email_reply_logs', ['message_id'], unique=False)
    op.create_table('automation_flows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('edges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_flows_pkey'))
    )
    op.create_index(op.f('ix_automation_flows_workspace_id'), 'automation_flows', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_automation_flows_name'), 'automation_flows', ['name'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('connected_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connected_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('integrations_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('integrations_pkey'))
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###