"""Add system_tag to templates

Revision ID: c1d13b97eac8
Revises: eeab75aa3311
Create Date: 2026-06-19 12:54:23.662742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d13b97eac8'
down_revision: Union[str, Sequence[str], None] = 'eeab75aa3311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('system_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'system_tag')
    # ### end Alembic commands ###
