"""add_credit_packs_and_ledger_updates

Revision ID: c38fa3b4e462
Revises: a4ae35413359
Create Date: 2026-06-19 05:20:26.191417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38fa3b4e462'
down_revision: Union[str, Sequence[str], None] = 'a4ae35413359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_packs_pack_id'), 'credit_packs', ['pack_id'], unique=True)
    
    # Add columns as nullable first to allow data migration
    op.add_column('token_ledger', sa.Column('credits_delta', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('token_ledger', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('token_ledger', sa.Column('balance_source', sa.String(length=20), nullable=True))
    
    # Migrate existing data
    op.execute("UPDATE token_ledger SET credits_delta = CAST(tokens_delta AS NUMERIC) / 1000.0000")
    op.execute(
        "UPDATE token_ledger SET balance_source = "
        "CASE "
        "  WHEN entry_type = 'purchase' THEN 'PURCHASED' "
        "  WHEN entry_type = 'overage' THEN 'OVERAGE' "
        "  ELSE 'INCLUDED' "
        "END"
    )
    
    # Alter column to be NOT NULL
    op.alter_column('token_ledger', 'credits_delta', nullable=False)

    # Seed default credit packs
    import uuid
    credit_packs_table = sa.table(
        'credit_packs',
        sa.column('id', sa.UUID()),
        sa.column('pack_id', sa.String()),
        sa.column('name', sa.String()),
        sa.column('amount', sa.Numeric()),
        sa.column('credits', sa.Integer()),
        sa.column('currency', sa.String()),
        sa.column('is_active', sa.Boolean()),
    )
    op.bulk_insert(
        credit_packs_table,
        [
            {
                "id": uuid.uuid4(),
                "pack_id": "credits_1k",
                "name": "Starter Pack",
                "amount": 999.00,
                "credits": 1000,
                "currency": "INR",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "pack_id": "credits_3k",
                "name": "Pro Pack",
                "amount": 2499.00,
                "credits": 3000,
                "currency": "INR",
                "is_active": True,
            },
            {
                "id": uuid.uuid4(),
                "pack_id": "credits_15k",
                "name": "Growth Pack",
                "amount": 9999.00,
                "credits": 15000,
                "currency": "INR",
                "is_active": True,
            },
        ]
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_ledger', 'balance_source')
    op.drop_column('token_ledger', 'tokens_used')
    op.drop_column('token_ledger', 'credits_delta')
    op.drop_index(op.f('ix_credit_packs_pack_id'), table_name='credit_packs')
    op.drop_table('credit_packs')
    # ### end Alembic commands ###
