"""Add workspace_id to sales_pipeline

Revision ID: c97898035ddd
Revises: ee9d22e89db3
Create Date: 2026-06-08 05:11:51.971518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c97898035ddd'
down_revision: Union[str, Sequence[str], None] = 'ee9d22e89db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_archive',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_type', postgresql.ENUM('USER', 'AI', 'AGENT', 'SYSTEM', name='sendertype', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('RECEIVED', 'SUGGESTED', 'SENT', 'DELIVERED', 'FAILED', name='messagestatus', create_type=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_archive_conversation_id'), 'messages_archive', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_archive_external_id'), 'messages_archive', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_archive_id'), 'messages_archive', ['id'], unique=False)
    op.alter_column('conversation_states', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_states', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_conversation_states_conversation_id'), 'conversation_states', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_states_workspace_id'), 'conversation_states', ['workspace_id'], unique=False)
    op.alter_column('conversations', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('followups', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_followups_workspace_id'), 'followups', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'followups', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.alter_column('human_escalations', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('human_escalations', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_human_escalations_conversation_id'), 'human_escalations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_human_escalations_workspace_id'), 'human_escalations', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'human_escalations', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'human_escalations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'human_escalations', 'users', ['user_id'], ['id'])
    op.alter_column('lead_score_history', 'lead_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('lead_score_history', 'score_before',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lead_score_history', 'score_after',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lead_score_history', 'behavioral_score_delta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lead_score_history', 'intent_score_delta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lead_score_history', 'reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lead_score_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_lead_score_history_created_at'), 'lead_score_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_score_history_lead_id'), 'lead_score_history', ['lead_id'], unique=False)
    op.alter_column('leads', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('leads', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('leads', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('leads', 'is_converted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_leads_conversation_id'), 'leads', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_leads_last_activity_at'), 'leads', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.add_column('learning_data', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.add_column('learning_data', sa.Column('profile_version', sa.String(), nullable=False))
    op.create_index(op.f('ix_learning_data_workspace_id'), 'learning_data', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'learning_data', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rag_feedback', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_rag_feedback_workspace_id'), 'rag_feedback', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'rag_feedback', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('sales_pipeline', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.add_column('sales_pipeline', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.add_column('sales_pipeline', sa.Column('intent', sa.String(length=255), nullable=True))
    op.add_column('sales_pipeline', sa.Column('lead_score', sa.String(length=50), nullable=True))
    op.add_column('sales_pipeline', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('sales_pipeline', sa.Column('objection_detected', sa.Boolean(), nullable=True))
    op.add_column('sales_pipeline', sa.Column('payment_required', sa.Boolean(), nullable=True))
    op.add_column('sales_pipeline', sa.Column('meeting_required', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_sales_pipeline_conversation_id'), 'sales_pipeline', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sales_pipeline_workspace_id'), 'sales_pipeline', ['workspace_id'], unique=False)
    op.create_unique_constraint('uq_sales_pipeline_scope', 'sales_pipeline', ['workspace_id', 'conversation_id'])
    op.drop_constraint(op.f('sales_pipeline_user_id_fkey'), 'sales_pipeline', type_='foreignkey')
    op.create_foreign_key(None, 'sales_pipeline', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales_pipeline', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sales_pipeline', 'expected_close_date')
    op.drop_column('sales_pipeline', 'deal_value')
    op.drop_column('sales_pipeline', 'user_id')
    op.drop_column('sales_pipeline', 'objections')
    op.drop_column('sales_pipeline', 'interest_level')
    op.drop_column('sales_pipeline', 'payment_completed')
    op.add_column('support_tickets', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.add_column('support_tickets', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_support_tickets_conversation_id'), 'support_tickets', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_workspace_id'), 'support_tickets', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'support_tickets', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'support_tickets', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.alter_column('template_logs', 'lead_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('template_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_template_logs_lead_id'), 'template_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_template_logs_template_id'), 'template_logs', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_logs_template_id'), table_name='template_logs')
    op.drop_index(op.f('ix_template_logs_lead_id'), table_name='template_logs')
    op.alter_column('template_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('template_logs', 'lead_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_support_tickets_workspace_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_conversation_id'), table_name='support_tickets')
    op.drop_column('support_tickets', 'conversation_id')
    op.drop_column('support_tickets', 'workspace_id')
    op.add_column('sales_pipeline', sa.Column('payment_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sales_pipeline', sa.Column('interest_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sales_pipeline', sa.Column('objections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sales_pipeline', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('sales_pipeline', sa.Column('deal_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sales_pipeline', sa.Column('expected_close_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_pipeline', type_='foreignkey')
    op.drop_constraint(None, 'sales_pipeline', type_='foreignkey')
    op.create_foreign_key(op.f('sales_pipeline_user_id_fkey'), 'sales_pipeline', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_sales_pipeline_scope', 'sales_pipeline', type_='unique')
    op.drop_index(op.f('ix_sales_pipeline_workspace_id'), table_name='sales_pipeline')
    op.drop_index(op.f('ix_sales_pipeline_conversation_id'), table_name='sales_pipeline')
    op.drop_column('sales_pipeline', 'meeting_required')
    op.drop_column('sales_pipeline', 'payment_required')
    op.drop_column('sales_pipeline', 'objection_detected')
    op.drop_column('sales_pipeline', 'confidence_score')
    op.drop_column('sales_pipeline', 'lead_score')
    op.drop_column('sales_pipeline', 'intent')
    op.drop_column('sales_pipeline', 'conversation_id')
    op.drop_column('sales_pipeline', 'workspace_id')
    op.drop_constraint(None, 'rag_feedback', type_='foreignkey')
    op.drop_index(op.f('ix_rag_feedback_workspace_id'), table_name='rag_feedback')
    op.alter_column('rag_feedback', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'learning_data', type_='foreignkey')
    op.drop_index(op.f('ix_learning_data_workspace_id'), table_name='learning_data')
    op.drop_column('learning_data', 'profile_version')
    op.drop_column('learning_data', 'workspace_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_last_activity_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_conversation_id'), table_name='leads')
    op.alter_column('leads', 'is_converted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('leads', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('leads', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('leads', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_lead_score_history_lead_id'), table_name='lead_score_history')
    op.drop_index(op.f('ix_lead_score_history_created_at'), table_name='lead_score_history')
    op.alter_column('lead_score_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('lead_score_history', 'reason',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lead_score_history', 'intent_score_delta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead_score_history', 'behavioral_score_delta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead_score_history', 'score_after',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead_score_history', 'score_before',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead_score_history', 'lead_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'human_escalations', type_='foreignkey')
    op.drop_constraint(None, 'human_escalations', type_='foreignkey')
    op.drop_constraint(None, 'human_escalations', type_='foreignkey')
    op.drop_index(op.f('ix_human_escalations_workspace_id'), table_name='human_escalations')
    op.drop_index(op.f('ix_human_escalations_conversation_id'), table_name='human_escalations')
    op.alter_column('human_escalations', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('human_escalations', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'followups', type_='foreignkey')
    op.drop_index(op.f('ix_followups_workspace_id'), table_name='followups')
    op.drop_column('followups', 'workspace_id')
    op.alter_column('conversations', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_conversation_states_workspace_id'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_conversation_id'), table_name='conversation_states')
    op.alter_column('conversation_states', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversation_states', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_messages_archive_id'), table_name='messages_archive')
    op.drop_index(op.f('ix_messages_archive_external_id'), table_name='messages_archive')
    op.drop_index(op.f('ix_messages_archive_conversation_id'), table_name='messages_archive')
    op.drop_table('messages_archive')
    # ### end Alembic commands ###
