"""sync all new columns

Revision ID: d3e91e9bc870
Revises: 
Create Date: 2026-03-18 11:22:38.655743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3e91e9bc870'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    op.drop_table('email_reply_logs')
    op.drop_index(op.f('ix_calendar_events_workspace_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_table('impersonation_sessions')
    op.create_index(op.f('ix_ai_actions_workspace_id'), 'ai_actions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_brain_workspace_id'), 'brain', ['workspace_id'], unique=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_followups_conversation_id'), 'followups', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('followups_conversation_id_fkey'), 'followups', type_='foreignkey')
    op.create_foreign_key(None, 'followups', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('promises', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('promises_user_id_fkey'), 'promises', type_='foreignkey')
    op.create_foreign_key(None, 'promises', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promises', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('workspace_members', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('workspaces', sa.Column('custom_token_limit', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('plan_type', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('workspaces_created_by_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_created_by_fkey'), 'workspaces', 'users', ['created_by'], ['id'])
    op.drop_column('workspaces', 'plan_type')
    op.drop_column('workspaces', 'custom_token_limit')
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.alter_column('workspace_members', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'promises', type_='foreignkey')
    op.drop_constraint(None, 'promises', type_='foreignkey')
    op.create_foreign_key(op.f('promises_user_id_fkey'), 'promises', 'users', ['user_id'], ['id'])
    op.alter_column('promises', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_constraint(None, 'followups', type_='foreignkey')
    op.create_foreign_key(op.f('followups_conversation_id_fkey'), 'followups', 'workspaces', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_followups_conversation_id'), table_name='followups')
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_brain_workspace_id'), table_name='brain')
    op.drop_index(op.f('ix_ai_actions_workspace_id'), table_name='ai_actions')
    op.create_table('impersonation_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('impersonation_sessions_admin_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('impersonation_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('impersonation_sessions_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('impersonation_sessions_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('google_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_events_pkey'))
    )
    op.create_index(op.f('ix_calendar_events_workspace_id'), 'calendar_events', ['workspace_id'], unique=False)
    op.create_table('email_reply_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reply_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('email_reply_logs_pkey'))
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('connected_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connected_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('integrations_pkey'))
    )
    # ### end Alembic commands ###
