"""initial_schema

Revision ID: ee9d22e89db3
Revises: 
Create Date: 2026-05-30 14:08:24.094937

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee9d22e89db3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_flows_name'), 'automation_flows', ['name'], unique=False)
    op.create_index(op.f('ix_automation_flows_workspace_id'), 'automation_flows', ['workspace_id'], unique=False)
    op.create_table('messages_archive',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_type', sa.Enum('USER', 'AI', 'AGENT', 'SYSTEM', name='sendertype'), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'SUGGESTED', 'SENT', 'DELIVERED', 'FAILED', name='messagestatus'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_archive_conversation_id'), 'messages_archive', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_archive_external_id'), 'messages_archive', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_archive_id'), 'messages_archive', ['id'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_env', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_name'), 'model_configs', ['name'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('message_limit', sa.Integer(), nullable=True),
    sa.Column('token_limit', sa.Integer(), nullable=True),
    sa.Column('price_per_extra_message', sa.Integer(), nullable=True),
    sa.Column('price_per_extra_token', sa.Integer(), nullable=True),
    sa.Column('workspace_limit', sa.Integer(), nullable=True),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', name='billing_cycle_enum'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('provider_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_event_id')
    )
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=False)
    op.create_table('impersonation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('billing_owner_id', sa.UUID(), nullable=True),
    sa.Column('provider_customer_id', sa.String(), nullable=True),
    sa.Column('custom_token_limit', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('overage_enabled', sa.Boolean(), nullable=False),
    sa.Column('meta_access_token', sa.Text(), nullable=True),
    sa.Column('meta_business_id', sa.String(length=255), nullable=True),
    sa.Column('meta_waba_id', sa.String(length=255), nullable=True),
    sa.Column('meta_phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('meta_display_phone', sa.String(length=50), nullable=True),
    sa.Column('meta_ig_id', sa.String(length=255), nullable=True),
    sa.Column('meta_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('twilio_account_sid', sa.Text(), nullable=True),
    sa.Column('twilio_auth_token', sa.Text(), nullable=True),
    sa.Column('twilio_phone_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['billing_owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_provider_customer_id'), 'workspaces', ['provider_customer_id'], unique=False)
    op.create_table('ai_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('intent_raw', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('mcp_decision', sa.String(length=50), nullable=True),
    sa.Column('mcp_reason', sa.Text(), nullable=True),
    sa.Column('rule_results', sa.JSON(), nullable=True),
    sa.Column('context_refs', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=True),
    sa.Column('human_override', sa.Boolean(), nullable=True),
    sa.Column('action_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_actions_workspace_id'), 'ai_actions', ['workspace_id'], unique=False)
    op.create_table('brain',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_workspace_id'), 'brain', ['workspace_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_time', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('google_event_id', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_google_event_id'), 'calendar_events', ['google_event_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_workspace_id'), 'calendar_events', ['workspace_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('last_category', sa.String(length=50), nullable=True),
    sa.Column('last_priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_threads_thread_id'), 'conversation_threads', ['thread_id'], unique=False)
    op.create_index(op.f('ix_conversation_threads_workspace_id'), 'conversation_threads', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'TWILIO', 'INSTAGRAM', 'EMAIL', 'WEB', name='channeltype'), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'SNOOZED', name='conversationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'phone', 'channel', name='uq_workspace_phone_channel')
    )
    op.create_index(op.f('ix_conversations_external_id'), 'conversations', ['external_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_phone'), 'conversations', ['phone'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('email_reply_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_reply_logs_message_id'), 'email_reply_logs', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_reply_logs_thread_id'), 'email_reply_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_email_reply_logs_workspace_id'), 'email_reply_logs', ['workspace_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_gmail_message_id'), 'emails', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_emails_sender'), 'emails', ['sender'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_index(op.f('ix_emails_workspace_id'), 'emails', ['workspace_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('connected_email', sa.String(length=255), nullable=True),
    sa.Column('connected_account_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_table('learning_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('profile_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_data_workspace_id'), 'learning_data', ['workspace_id'], unique=False)
    op.create_table('mcp_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entities_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('requires_user_permission', sa.Boolean(), nullable=True),
    sa.Column('user_action', sa.String(length=20), nullable=True),
    sa.Column('executed_actions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_decisions_message_id'), 'mcp_decisions', ['message_id'], unique=False)
    op.create_index(op.f('ix_mcp_decisions_thread_id'), 'mcp_decisions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_mcp_decisions_workspace_id'), 'mcp_decisions', ['workspace_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_workspace_id'), 'media_files', ['workspace_id'], unique=False)
    op.create_table('rag_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('rewritten_query', sa.Text(), nullable=True),
    sa.Column('selected_tool', sa.String(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_feedback_workspace_id'), 'rag_feedback', ['workspace_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trialing', 'past_due', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', name='billing_cycle_enum'), nullable=False),
    sa.Column('is_admin_override', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_provider_subscription_id'), 'subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_workspace_id'), 'subscriptions', ['workspace_id'], unique=False)
    op.create_index('uq_active_subscription', 'subscriptions', ['workspace_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_index('uq_provider_subscription', 'subscriptions', ['provider', 'provider_subscription_id'], unique=True, postgresql_where=sa.text('provider_subscription_id IS NOT NULL'))
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('meta_template_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('ai_learning_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('ai_action_id', sa.UUID(), nullable=True),
    sa.Column('mcp_verdict', sa.String(length=50), nullable=True),
    sa.Column('mcp_confidence', sa.Float(), nullable=True),
    sa.Column('feedback_type', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'SAVE_TO_BRAIN', 'NO_FEEDBACK', name='feedbacktype'), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('feedback_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_success', sa.Boolean(), nullable=True),
    sa.Column('user_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('pattern_tags', sa.JSON(), nullable=True),
    sa.Column('used_in_training', sa.Boolean(), nullable=True),
    sa.Column('promoted_to_rule', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ai_action_id'], ['ai_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brain_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['brain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_chunks_workspace_id'), 'brain_chunks', ['workspace_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('last_intent', sa.String(length=255), nullable=True),
    sa.Column('last_agent', sa.String(length=100), nullable=True),
    sa.Column('human_takeover', sa.Boolean(), nullable=True),
    sa.Column('ai_paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_count', sa.Integer(), nullable=True),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('last_message_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'conversation_id', name='uq_conversation_states_workspace_conversation')
    )
    op.create_index(op.f('ix_conversation_states_conversation_id'), 'conversation_states', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_states_workspace_id'), 'conversation_states', ['workspace_id'], unique=False)
    op.create_table('flow_execution_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('active_flow_id', sa.UUID(), nullable=True),
    sa.Column('current_node_id', sa.String(), nullable=True),
    sa.Column('conversation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runtime_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_button', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('button_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_question', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loop_count', sa.Integer(), nullable=True),
    sa.Column('last_node_id', sa.String(), nullable=True),
    sa.Column('last_context_checkpoint_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', name='uq_flow_execution_state_conversation')
    )
    op.create_index(op.f('ix_flow_execution_states_active_flow_id'), 'flow_execution_states', ['active_flow_id'], unique=False)
    op.create_index(op.f('ix_flow_execution_states_conversation_id'), 'flow_execution_states', ['conversation_id'], unique=False)
    op.create_table('flow_execution_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_execution_traces_conversation_id'), 'flow_execution_traces', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_flow_execution_traces_event_type'), 'flow_execution_traces', ['event_type'], unique=False)
    op.create_index(op.f('ix_flow_execution_traces_flow_id'), 'flow_execution_traces', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_execution_traces_node_id'), 'flow_execution_traces', ['node_id'], unique=False)
    op.create_index(op.f('ix_flow_execution_traces_status'), 'flow_execution_traces', ['status'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('followup_count', sa.Integer(), nullable=True),
    sa.Column('mcp_decision', sa.String(length=50), nullable=True),
    sa.Column('mcp_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_conversation_id'), 'followups', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_followups_workspace_id'), 'followups', ['workspace_id'], unique=False)
    op.create_table('human_escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_escalations_conversation_id'), 'human_escalations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_human_escalations_workspace_id'), 'human_escalations', ['workspace_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'paid', 'void', name='invoicestatus'), nullable=False),
    sa.Column('razorpay_invoice_id', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_razorpay_invoice_id'), 'invoices', ['razorpay_invoice_id'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('timeline', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_location', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('qualification', sa.String(length=50), nullable=True),
    sa.Column('lead_score', sa.Float(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_node', sa.Integer(), nullable=True),
    sa.Column('total_nodes', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('behavioral_score', sa.Integer(), nullable=True),
    sa.Column('semantic_intent_score', sa.Integer(), nullable=True),
    sa.Column('lead_tier', sa.String(length=50), nullable=True),
    sa.Column('intent_signals', sa.JSON(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_raw', sa.String(length=255), nullable=True),
    sa.Column('template_attempts', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('conversion_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('converted_product', sa.String(length=255), nullable=True),
    sa.Column('conversion_notes', sa.Text(), nullable=True),
    sa.Column('demo_requested', sa.Boolean(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_link', sa.Text(), nullable=True),
    sa.Column('last_agent', sa.String(length=100), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'conversation_id', name='uq_leads_scope')
    )
    op.create_index(op.f('ix_leads_conversation_id'), 'leads', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_leads_last_activity_at'), 'leads', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_score'), 'leads', ['score'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_type', sa.Enum('USER', 'AI', 'AGENT', 'SYSTEM', name='sendertype'), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'SUGGESTED', 'SENT', 'DELIVERED', 'FAILED', name='messagestatus'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_message_external_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('twilio_sid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbound_messages_conv_seq', 'outbound_messages', ['conversation_id', 'sequence'], unique=True)
    op.create_index(op.f('ix_outbound_messages_conversation_id'), 'outbound_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_flow_id'), 'outbound_messages', ['flow_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_message_type'), 'outbound_messages', ['message_type'], unique=False)
    op.create_index('ix_outbound_messages_one_active', 'outbound_messages', ['conversation_id'], unique=True, postgresql_where=sa.text("status IN ('in_progress', 'dispatched')"))
    op.create_index(op.f('ix_outbound_messages_status'), 'outbound_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_messages_twilio_sid'), 'outbound_messages', ['twilio_sid'], unique=False)
    op.create_table('sales_pipeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('interest_level', sa.String(length=50), nullable=True),
    sa.Column('objections', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'conversation_id', name='uq_sales_pipeline_scope')
    )
    op.create_index(op.f('ix_sales_pipeline_conversation_id'), 'sales_pipeline', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sales_pipeline_workspace_id'), 'sales_pipeline', ['workspace_id'], unique=False)
    op.create_table('scheduled_resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('inbound_text', sa.String(), nullable=False),
    sa.Column('msg_sequence_val', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_resumes_flow_id'), 'scheduled_resumes', ['flow_id'], unique=False)
    op.create_index('ix_scheduled_resumes_pending_run_at', 'scheduled_resumes', ['status', 'run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_resumes_status'), 'scheduled_resumes', ['status'], unique=False)
    op.create_table('subscription_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('old_plan_id', sa.UUID(), nullable=True),
    sa.Column('new_plan_id', sa.UUID(), nullable=True),
    sa.Column('old_price', sa.Integer(), nullable=True),
    sa.Column('new_price', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['new_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['old_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_conversation_id'), 'support_tickets', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_workspace_id'), 'support_tickets', ['workspace_id'], unique=False)
    op.create_table('usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('messages_used', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('overage_messages', sa.Integer(), nullable=True),
    sa.Column('overage_tokens', sa.Integer(), nullable=True),
    sa.Column('billed', sa.Boolean(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'subscription_id', 'period_start', name='uq_usage_period')
    )
    op.create_index(op.f('ix_usage_subscription_id'), 'usage', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_workspace_id'), 'usage', ['workspace_id'], unique=False)
    op.create_table('lead_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('score_before', sa.Integer(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('behavioral_score_delta', sa.Integer(), nullable=False),
    sa.Column('intent_score_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_score_history_created_at'), 'lead_score_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_score_history_lead_id'), 'lead_score_history', ['lead_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('billing_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('provider_order_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_workspace_id'), 'payments', ['workspace_id'], unique=False)
    op.create_index('uq_payment_provider_payment_id', 'payments', ['provider', 'provider_payment_id'], unique=True, postgresql_where=sa.text('provider_payment_id IS NOT NULL'))
    op.create_table('template_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_type', sa.String(length=50), nullable=True),
    sa.Column('score_impact', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_logs_lead_id'), 'template_logs', ['lead_id'], unique=False)
    op.create_index(op.f('ix_template_logs_template_id'), 'template_logs', ['template_id'], unique=False)
    op.create_table('token_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tokens_delta', sa.Integer(), nullable=False),
    sa.Column('reference_key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_key', name='uq_token_ledger_reference_key')
    )
    op.create_index(op.f('ix_token_ledger_expires_at'), 'token_ledger', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_ledger_payment_id'), 'token_ledger', ['payment_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_reference_key'), 'token_ledger', ['reference_key'], unique=False)
    op.create_index(op.f('ix_token_ledger_subscription_id'), 'token_ledger', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_token_ledger_workspace_id'), 'token_ledger', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_ledger_workspace_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_subscription_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_reference_key'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_payment_id'), table_name='token_ledger')
    op.drop_index(op.f('ix_token_ledger_expires_at'), table_name='token_ledger')
    op.drop_table('token_ledger')
    op.drop_index(op.f('ix_template_logs_template_id'), table_name='template_logs')
    op.drop_index(op.f('ix_template_logs_lead_id'), table_name='template_logs')
    op.drop_table('template_logs')
    op.drop_index('uq_payment_provider_payment_id', table_name='payments', postgresql_where=sa.text('provider_payment_id IS NOT NULL'))
    op.drop_index(op.f('ix_payments_workspace_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_lead_score_history_lead_id'), table_name='lead_score_history')
    op.drop_index(op.f('ix_lead_score_history_created_at'), table_name='lead_score_history')
    op.drop_table('lead_score_history')
    op.drop_index(op.f('ix_usage_workspace_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_subscription_id'), table_name='usage')
    op.drop_table('usage')
    op.drop_index(op.f('ix_support_tickets_workspace_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_conversation_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_table('subscription_history')
    op.drop_index(op.f('ix_scheduled_resumes_status'), table_name='scheduled_resumes')
    op.drop_index('ix_scheduled_resumes_pending_run_at', table_name='scheduled_resumes')
    op.drop_index(op.f('ix_scheduled_resumes_flow_id'), table_name='scheduled_resumes')
    op.drop_table('scheduled_resumes')
    op.drop_index(op.f('ix_sales_pipeline_workspace_id'), table_name='sales_pipeline')
    op.drop_index(op.f('ix_sales_pipeline_conversation_id'), table_name='sales_pipeline')
    op.drop_table('sales_pipeline')
    op.drop_index(op.f('ix_outbound_messages_twilio_sid'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_status'), table_name='outbound_messages')
    op.drop_index('ix_outbound_messages_one_active', table_name='outbound_messages', postgresql_where=sa.text("status IN ('in_progress', 'dispatched')"))
    op.drop_index(op.f('ix_outbound_messages_message_type'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_flow_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_conversation_id'), table_name='outbound_messages')
    op.drop_index('ix_outbound_messages_conv_seq', table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_last_activity_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_conversation_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_invoices_razorpay_invoice_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_human_escalations_workspace_id'), table_name='human_escalations')
    op.drop_index(op.f('ix_human_escalations_conversation_id'), table_name='human_escalations')
    op.drop_table('human_escalations')
    op.drop_index(op.f('ix_followups_workspace_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_conversation_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_flow_execution_traces_status'), table_name='flow_execution_traces')
    op.drop_index(op.f('ix_flow_execution_traces_node_id'), table_name='flow_execution_traces')
    op.drop_index(op.f('ix_flow_execution_traces_flow_id'), table_name='flow_execution_traces')
    op.drop_index(op.f('ix_flow_execution_traces_event_type'), table_name='flow_execution_traces')
    op.drop_index(op.f('ix_flow_execution_traces_conversation_id'), table_name='flow_execution_traces')
    op.drop_table('flow_execution_traces')
    op.drop_index(op.f('ix_flow_execution_states_conversation_id'), table_name='flow_execution_states')
    op.drop_index(op.f('ix_flow_execution_states_active_flow_id'), table_name='flow_execution_states')
    op.drop_table('flow_execution_states')
    op.drop_index(op.f('ix_conversation_states_workspace_id'), table_name='conversation_states')
    op.drop_index(op.f('ix_conversation_states_conversation_id'), table_name='conversation_states')
    op.drop_table('conversation_states')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_brain_chunks_workspace_id'), table_name='brain_chunks')
    op.drop_table('brain_chunks')
    op.drop_table('ai_learning_events')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_table('templates')
    op.drop_index('uq_provider_subscription', table_name='subscriptions', postgresql_where=sa.text('provider_subscription_id IS NOT NULL'))
    op.drop_index('uq_active_subscription', table_name='subscriptions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_subscriptions_workspace_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_rag_feedback_workspace_id'), table_name='rag_feedback')
    op.drop_table('rag_feedback')
    op.drop_index(op.f('ix_media_files_workspace_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_mcp_decisions_workspace_id'), table_name='mcp_decisions')
    op.drop_index(op.f('ix_mcp_decisions_thread_id'), table_name='mcp_decisions')
    op.drop_index(op.f('ix_mcp_decisions_message_id'), table_name='mcp_decisions')
    op.drop_table('mcp_decisions')
    op.drop_index(op.f('ix_learning_data_workspace_id'), table_name='learning_data')
    op.drop_table('learning_data')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_emails_workspace_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_sender'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_message_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_email_reply_logs_workspace_id'), table_name='email_reply_logs')
    op.drop_index(op.f('ix_email_reply_logs_thread_id'), table_name='email_reply_logs')
    op.drop_index(op.f('ix_email_reply_logs_message_id'), table_name='email_reply_logs')
    op.drop_table('email_reply_logs')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_phone'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_external_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_conversation_threads_workspace_id'), table_name='conversation_threads')
    op.drop_index(op.f('ix_conversation_threads_thread_id'), table_name='conversation_threads')
    op.drop_table('conversation_threads')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_calendar_events_workspace_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_google_event_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_brain_workspace_id'), table_name='brain')
    op.drop_table('brain')
    op.drop_index(op.f('ix_ai_actions_workspace_id'), table_name='ai_actions')
    op.drop_table('ai_actions')
    op.drop_index(op.f('ix_workspaces_provider_customer_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('impersonation_sessions')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_model_configs_name'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_messages_archive_id'), table_name='messages_archive')
    op.drop_index(op.f('ix_messages_archive_external_id'), table_name='messages_archive')
    op.drop_index(op.f('ix_messages_archive_conversation_id'), table_name='messages_archive')
    op.drop_table('messages_archive')
    op.drop_index(op.f('ix_automation_flows_workspace_id'), table_name='automation_flows')
    op.drop_index(op.f('ix_automation_flows_name'), table_name='automation_flows')
    op.drop_table('automation_flows')
    # ### end Alembic commands ###
