"""add_customer_name_contact_to_support_tickets

Revision ID: eeab75aa3311
Revises: 7273795b5903
Create Date: 2026-06-19 11:15:54.847235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeab75aa3311'
down_revision: Union[str, Sequence[str], None] = '7273795b5903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('support_tickets', sa.Column('customer_contact', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'customer_contact')
    op.drop_column('support_tickets', 'customer_name')
    # ### end Alembic commands ###
