"""add_header_footer_cta_to_templates

Revision ID: eff0dfabf280
Revises: c97898035ddd
Create Date: 2026-06-11 12:10:02.167141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff0dfabf280'
down_revision: Union[str, Sequence[str], None] = 'c97898035ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('header', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('footer', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('cta', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('cta_btn_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'cta_btn_title')
    op.drop_column('templates', 'cta')
    op.drop_column('templates', 'footer')
    op.drop_column('templates', 'header')
    # ### end Alembic commands ###
