"""Add overage_enabled to Workspace

Revision ID: fd44bd45eca9
Revises: 3c91261414a7
Create Date: 2026-05-25 09:45:01.183944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd44bd45eca9'
down_revision: Union[str, Sequence[str], None] = '3c91261414a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_score_history', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('leads', 'behavioral_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('leads', 'semantic_intent_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('leads', 'lead_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'cold'::character varying"))
    op.add_column(
    'workspaces',
    sa.Column(
        'overage_enabled',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'overage_enabled')
    op.alter_column('leads', 'lead_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'cold'::character varying"))
    op.alter_column('leads', 'semantic_intent_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('leads', 'behavioral_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('lead_score_history', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    # ### end Alembic commands ###
