"""device_session_separation

Revision ID: ff3726b9699e
Revises: 08e673f229ae
Create Date: 2026-07-15 15:33:34.600436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff3726b9699e'
down_revision: Union[str, Sequence[str], None] = '08e673f229ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('browser_name', sa.String(), nullable=True),
    sa.Column('browser_version', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('latest_language', sa.String(), nullable=True),
    sa.Column('latest_timezone', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_by', sa.String(), nullable=True),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_user_device_fingerprint')
    )
    op.create_index(op.f('ix_user_devices_fingerprint'), 'user_devices', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('browser_name', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_device_id'), 'login_history', ['device_id'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.drop_index(op.f('ix_flow_pack_purchases_status'), table_name='flow_pack_purchases')
    op.drop_column('plans', 'trial_days')
    op.drop_column('subscriptions', 'trial_end')
    op.drop_column('subscriptions', 'trial_start')
    op.add_column('user_sessions', sa.Column('device_id', sa.UUID(), nullable=True))
    op.add_column('user_sessions', sa.Column('refresh_token_hash', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('user_agent', sa.String(), nullable=False))
    op.add_column('user_sessions', sa.Column('revoked', sa.Boolean(), nullable=False))
    op.add_column('user_sessions', sa.Column('revoked_by', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_sessions', 'user_devices', ['device_id'], ['id'], ondelete='SET NULL')
    op.drop_column('user_sessions', 'device_info')
    op.drop_column('user_sessions', 'is_blocked')
    op.alter_column('users', 'platform_role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('user', 'platform_admin', name='platformrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'platform_role',
               existing_type=sa.Enum('user', 'platform_admin', name='platformrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.add_column('user_sessions', sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_sessions', sa.Column('device_info', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_id'), table_name='user_sessions')
    op.drop_column('user_sessions', 'expires_at')
    op.drop_column('user_sessions', 'revoked_by')
    op.drop_column('user_sessions', 'revoked')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'refresh_token_hash')
    op.drop_column('user_sessions', 'device_id')
    op.add_column('subscriptions', sa.Column('trial_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('trial_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('trial_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_flow_pack_purchases_status'), 'flow_pack_purchases', ['status'], unique=False)
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_device_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_fingerprint'), table_name='user_devices')
    op.drop_table('user_devices')
    # ### end Alembic commands ###
